/**
 * create a object of Leaf and contain it's id and name
 */
var Leaf = {};
Leaf.id = 'leaf';
Leaf.series = 'leaf';
Leaf.seriesClass = 'leafSeries';
Leaf.kits = {
	'sensorkit': SensorKit,
	'autoKit': SensorKit,
}
Leaf.seriesImg = './device/leaf/img/leaf-大.png';
Leaf.serieSmallImg = './device/leaf/img/leaf-小.png';
Leaf.img = CORE_DIR + 'device/' + Leaf.id + '/img/' + Leaf.id + '_board' + '.png'
Leaf.width = 64.14;
Leaf.height = 40.65;
Leaf.pinWidth = 12;
Leaf.pinHeight = 12;
Leaf.name = "Leaf";
Leaf.active = 'active';
Leaf.functions = [
	"remote",
	"routing",
	"bluetooth",
	"play",
]

Leaf.pins = [
	{
		'id': 1,
		'name': 'A0',
		'x': 56.52,
		'y': 2.54,
		'width': Leaf.pinWidth,
		'height': Leaf.pinHeight,
		'isSource': false,
		'property': ["ain"],
		'type': 'analog',
	},
	{
		'id': 2,
		'name': 'A1',
		'x': 53.98,
		'y': 2.54,
		'width': Leaf.pinWidth,
		'height': Leaf.pinHeight,
		'isSource': false,
		'property': ["ain"],
		'type': 'analog',
	},
	{
		'id': 3,
		'name': 'A2',
		'x': 51.44,
		'y': 2.54,
		'width': Leaf.pinWidth,
		'height': Leaf.pinHeight,
		'isSource': false,
		'property': ["ain"],
		'type': 'analog',
	},
	{
		'id': 4,
		'name': 'A3',
		'x': 48.9,
		'y': 2.54,
		'width': Leaf.pinWidth,
		'height': Leaf.pinHeight,
		'isSource': false,
		'property': ["ain"],
		'type': 'analog',
	},
	{
		'id': 5,
		'name': 'A4',
		'x': 46.36,
		'y': 2.54,
		'width': Leaf.pinWidth,
		'height': Leaf.pinHeight,
		'isSource': false,
		'property': ["ain"],
		'type': 'analog',
	},
	{
		'id': 6,
		'name': 'A5',
		'x': 43.82,
		'y': 2.54,
		'width': Leaf.pinWidth,
		'height': Leaf.pinHeight,
		'isSource': false,
		'property': ["ain"],
		'type': 'analog',
	},
	{
		'id': 7,
		'name': 'A6',
		'x': 41.28,
		'y': 2.54,
		'width': Leaf.pinWidth,
		'height': Leaf.pinHeight,
		'isSource': false,
		'property': ["ain"],
		'type': 'analog',
	},
	{
		'id': 8,
		'name': 'A7',
		'x': 38.74,
		'y': 2.54,
		'width': Leaf.pinWidth,
		'height': Leaf.pinHeight,
		'isSource': false,
		'property': ["ain"],
		'type': 'analog',
	},
	{
		'id': 9,
		'name': 'A8',
		'x': 36.2,
		'y': 2.54,
		'width': Leaf.pinWidth,
		'height': Leaf.pinHeight,
		'isSource': false,
		'property': ["ain"],
		'type': 'analog',
	},
	{
		'id': 10,
		'name': 'A9',
		'x': 33.66,
		'y': 2.54,
		'width': Leaf.pinWidth,
		'height': Leaf.pinHeight,
		'isSource': false,
		'property': ["ain"],
		'type': 'analog',
	},
	{
		'id': 11,
		'name': 'A10',
		'x': 31.12,
		'y': 2.54,
		'width': Leaf.pinWidth,
		'height': Leaf.pinHeight,
		'isSource': false,
		'property': ["ain"],
		'type': 'analog',
	},
	{
		'id': 12,
		'name': 'A11',
		'x': 28.58,
		'y': 2.54,
		'width': Leaf.pinWidth,
		'height': Leaf.pinHeight,
		'isSource': false,
		'property': ["ain"],
		'type': 'analog',
	},
	{
		'id': 13,
		'name': 'A12',
		'x': 26.04,
		'y': 2.54,
		'width': Leaf.pinWidth,
		'height': Leaf.pinHeight,
		'isSource': false,
		'property': ["ain"],
		'type': 'analog',
	},
	{
		'id': 14,
		'name': 'A13',
		'x': 23.5,
		'y': 2.54,
		'width': Leaf.pinWidth,
		'height': Leaf.pinHeight,
		'isSource': false,
		'property': ["ain"],
		'type': 'analog',
	},
	{
		'id': 15,
		'name': 'GND',
		'x': 20.96,
		'y': 2.54,
		'width': Leaf.pinWidth,
		'height': Leaf.pinHeight,
		'isSource': false,
		'property': ["GND"],
		'type': 'ground',
	},
	{
		'id': 16,
		'name': '3V3',
		'x': 18.42,
		'y': 2.54,
		'width': Leaf.pinWidth,
		'height': Leaf.pinHeight,
		'isSource': false,
		'property': ["3V3"],
		'type': 'power',
	},
	{
		'id': 17,
		'name': 'RST',
		'x': 15.88,
		'y': 2.54,
		'width': Leaf.pinWidth,
		'height': Leaf.pinHeight,
		'isSource': false,
		'property': ["RST"],
		'type': 'other',
	},
	{
		'id': 18,
		'name': 'DFU',
		'x': 13.34,
		'y': 2.54,
		'width': Leaf.pinWidth,
		'height': Leaf.pinHeight,
		'isSource': false,
		'property': ["DFU"],
		'type': 'other',
	},
	{
		'id': 19,
		'name': 'VIN',
		'x': 13.34,
		'y': 38.11,
		'width': Leaf.pinWidth,
		'height': Leaf.pinHeight,
		'isSource': false,
		'property': ["VIN"],
		'type': 'power',
	},
	{
		'id': 20,
		'name': '5V',
		'x': 15.88,
		'y': 38.11,
		'width': Leaf.pinWidth,
		'height': Leaf.pinHeight,
		'isSource': false,
		'property': ["5V"],
		'type': 'power',
	},
	{
		'id': 21,
		'name': '3V3',
		'x': 18.42,
		'y': 38.11,
		'width': Leaf.pinWidth,
		'height': Leaf.pinHeight,
		'isSource': false,
		'property': ["3V3"],
		'type': 'power',
	},
	{
		'id': 22,
		'name': 'GND',
		'x': 20.96,
		'y': 38.11,
		'width': Leaf.pinWidth,
		'height': Leaf.pinHeight,
		'isSource': false,
		'property': ["GND"],
		'type': 'ground',
	},
	{
		'id': 23,
		'name': 'D0',
		'x': 23.5,
		'y': 38.11,
		'width': Leaf.pinWidth,
		'height': Leaf.pinHeight,
		'isSource': false,
		'property': ["din", "dout"],
		'type': 'digital',
	},
	{
		'id': 24,
		'name': 'D1',
		'x': 26.04,
		'y': 38.11,
		'width': Leaf.pinWidth,
		'height': Leaf.pinHeight,
		'isSource': false,
		'property': ["din", "dout"],
		'type': 'digital',
	},
	{
		'id': 25,
		'name': 'D2',
		'x': 28.58,
		'y': 38.11,
		'width': Leaf.pinWidth,
		'height': Leaf.pinHeight,
		'isSource': false,
		'property': ["din", "dout"],
		'type': 'digital',
	},
	{
		'id': 26,
		'name': 'D3',
		'x': 31.12,
		'y': 38.11,
		'width': Leaf.pinWidth,
		'height': Leaf.pinHeight,
		'isSource': false,
		'property': ["din", "dout"],
		'type': 'digital',
	},
	{
		'id': 27,
		'name': 'D4',
		'x': 33.66,
		'y': 38.11,
		'width': Leaf.pinWidth,
		'height': Leaf.pinHeight,
		'isSource': false,
		'property': ["din", "dout"],
		'type': 'digital',
	},
	{
		'id': 28,
		'name': 'D5',
		'x': 36.2,
		'y': 38.11,
		'width': Leaf.pinWidth,
		'height': Leaf.pinHeight,
		'isSource': false,
		'property': ["din", "dout"],
		'type': 'digital',
	},
	{
		'id': 29,
		'name': 'D6',
		'x': 38.74,
		'y': 38.11,
		'width': Leaf.pinWidth,
		'height': Leaf.pinHeight,
		'isSource': false,
		'property': ["din", "dout"],
		'type': 'digital',
	},
	{
		'id': 30,
		'name': 'D7',
		'x': 41.28,
		'y': 38.11,
		'width': Leaf.pinWidth,
		'height': Leaf.pinHeight,
		'isSource': false,
		'property': ["din", "dout"],
		'type': 'digital',
	},
	{
		'id': 31,
		'name': 'D8',
		'x': 43.82,
		'y': 38.11,
		'width': Leaf.pinWidth,
		'height': Leaf.pinHeight,
		'isSource': false,
		'property': ["din", "dout"],
		'type': 'digital',
	},
	{
		'id': 32,
		'name': 'D9',
		'x': 46.36,
		'y': 38.11,
		'width': Leaf.pinWidth,
		'height': Leaf.pinHeight,
		'isSource': false,
		'property': ["din", "dout"],
		'type': 'digital',
	},
	{
		'id': 33,
		'name': 'D10',
		'x': 48.9,
		'y': 38.11,
		'width': Leaf.pinWidth,
		'height': Leaf.pinHeight,
		'isSource': false,
		'property': ["din", "dout"],
		'type': 'digital',
	},
	{
		'id': 34,
		'name': 'D11',
		'x': 51.44,
		'y': 38.11,
		'width': Leaf.pinWidth,
		'height': Leaf.pinHeight,
		'isSource': false,
		'property': ["din", "dout"],
		'type': 'digital',
	},
	{
		'id': 35,
		'name': 'D12',
		'x': 53.98,
		'y': 38.11,
		'width': Leaf.pinWidth,
		'height': Leaf.pinHeight,
		'isSource': false,
		'property': ["din", "dout"],
		'type': 'digital',
	},
	{
		'id': 36,
		'name': 'D13',
		'x': 56.52,
		'y': 38.11,
		'width': Leaf.pinWidth,
		'height': Leaf.pinHeight,
		'isSource': false,
		'property': ["din", "dout"],
		'type': 'digital',
	},
]

Leaf.init = function () {
	// console.log('Leaf.init')
	Leaf.name = MSG.catLeaf;
	Leaf.description = MSG.leaf_description;
}